- hosts: localhost
  tasks:
   - ec2_instance:
        region: ap-south-1
        image_id: ami-0bcf5425cdc1d8a85
        instance_type: t2.micro
        vpc_subnet_id: subnet-630b010b
        security_group: sg-02c494868ecff0627 
        key_name: awsKeypair
        name: OS_from_Ansible
        state: present
        aws_access_key: <add your access  key here>
        aws_secret_key: <add your secret kry here>
